-- create_tables.sql

-- Categories table
CREATE TABLE IF NOT EXISTS public.categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  slug TEXT NOT NULL UNIQUE,
  description TEXT,
  image TEXT
);

-- Products table
CREATE TABLE IF NOT EXISTS public.products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  slug TEXT NOT NULL UNIQUE,
  description TEXT,
  excerpt TEXT,
  price NUMERIC NOT NULL,
  regular_price NUMERIC NOT NULL,
  sale_price NUMERIC,
  sku TEXT,
  stock INTEGER NOT NULL DEFAULT 0,
  stock_status TEXT NOT NULL DEFAULT 'instock',
  weight NUMERIC NOT NULL DEFAULT 0,
  image TEXT
);

-- Join table for many‑to‑many product ↔ category relationship
CREATE TABLE IF NOT EXISTS public.product_categories (
  product_id BIGINT NOT NULL REFERENCES public.products(id) ON DELETE CASCADE,
  category_id BIGINT NOT NULL REFERENCES public.categories(id) ON DELETE CASCADE,
  PRIMARY KEY (product_id, category_id)
);

-- Settings (key‑value pairs used by the app)
CREATE TABLE IF NOT EXISTS public.settings (
  key TEXT PRIMARY KEY,
  value TEXT NOT NULL
);

-- Users table (for authentication)
CREATE TABLE IF NOT EXISTS public.users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email TEXT NOT NULL UNIQUE,
  role TEXT NOT NULL,
  password_hash TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Optional: Orders table (basic fields based on the Order interface)
CREATE TABLE IF NOT EXISTS public.orders (
  id TEXT PRIMARY KEY,
  customer_name TEXT NOT NULL,
  customer_email TEXT NOT NULL,
  shipping_address TEXT NOT NULL,
  shipping_city TEXT NOT NULL,
  shipping_postcode TEXT NOT NULL,
  shipping_phone TEXT NOT NULL,
  total_amount NUMERIC NOT NULL,
  shipping_cost NUMERIC NOT NULL,
  status TEXT NOT NULL,
  apc_tracking_number TEXT,
  apc_label_url TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Order Items table (linking orders to products)
CREATE TABLE IF NOT EXISTS public.order_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id TEXT NOT NULL REFERENCES public.orders(id) ON DELETE CASCADE,
  product_id BIGINT REFERENCES public.products(id) ON DELETE SET NULL,
  product_title TEXT NOT NULL,
  quantity INTEGER NOT NULL DEFAULT 1,
  price NUMERIC NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
